# Generated by Django 4.1.5 on 2023-01-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Activity Name')),
                ('address', models.CharField(max_length=75, null=True, verbose_name='Activity Address')),
                ('price', models.CharField(max_length=24, verbose_name='Activity Price')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=24, verbose_name='Trip Title')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=24, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=24, verbose_name='Last Name')),
                ('username', models.CharField(max_length=24, verbose_name='Username')),
                ('password', models.CharField(max_length=24, verbose_name='Password')),
                ('email', models.EmailField(max_length=24, verbose_name='Email')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='backend.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_invites', to='backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(related_name='trips', through='backend.Trip_Invite', to='backend.user'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Hotel Name')),
                ('address', models.CharField(max_length=75, null=True, verbose_name='Hotel Address')),
                ('price', models.CharField(max_length=24, verbose_name='Hotel Price')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depart_city', models.CharField(max_length=50, verbose_name='Departure City')),
                ('depart_time', models.CharField(max_length=10, verbose_name='Departure Time')),
                ('arrival_city', models.CharField(max_length=50, verbose_name='Arrival City')),
                ('arrive_time', models.CharField(max_length=10, verbose_name='Arrival Time')),
                ('price', models.CharField(max_length=24, verbose_name='Flight Price')),
                ('layover_id', models.ManyToManyField(blank=True, null=True, to='backend.flight')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.activity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.user')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.flight')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.hotel')),
                ('parent_comment', models.ManyToManyField(blank=True, null=True, related_name='child_comments', to='backend.comment')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.trip')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.trip'),
        ),
    ]
