# Generated by Django 4.1.5 on 2023-01-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_user_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_invite',
            old_name='user',
            new_name='member',
        ),
    ]
