# Generated by Django 4.1.5 on 2023-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_user_trip_invite_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ManyToManyField(blank=True, related_name='child_comments', to='backend.comment'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='layover_id',
            field=models.ManyToManyField(blank=True, related_name='layovers', to='backend.flight'),
        ),
    ]
