# Generated by Django 4.1.5 on 2023-01-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_comment_parent_comment_alter_flight_layover_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(default='Comment Error', max_length=240, verbose_name='Message'),
        ),
    ]
