# Generated by Django 4.1.5 on 2023-01-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
