# Generated by Django 4.1.5 on 2023-01-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_activity_votes_flight_votes_hotel_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
