# Generated by Django 4.1.5 on 2023-01-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_flight_arrive_date_flight_depart_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_city',
            new_name='arrive_city',
        ),
    ]
