# Generated by Django 4.1.5 on 2023-02-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_arrival_city_flight_arrive_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.trip'),
        ),
    ]
