# Generated by Django 4.1.5 on 2023-02-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default='0000-01-01', null=True),
        ),
    ]
