# Generated by Django 4.1.5 on 2023-02-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_invite',
            name='departure_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
