# Generated by Django 4.1.5 on 2023-02-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_trip_invite_departure_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
