# Generated by Django 4.1.5 on 2023-02-08 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='votes',
        ),
        migrations.CreateModel(
            name='Vote_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='backend.activity')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='backend.flight')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='backend.hotel')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_history', to='backend.member')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='votes',
            field=models.ManyToManyField(blank=True, to='backend.member'),
        ),
    ]
