# Generated by Django 4.1.5 on 2023-02-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_voted_flight_voters_remove_hotel_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_invite',
            name='pending',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
