# Generated by Django 4.1.5 on 2023-02-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_trip_invite_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='flight',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='link'),
        ),
    ]
